apiVersion: grafana.grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: my-grafana-instance
  namespace: monitoring
spec:
  ingress:
    enabled: false
  config:
    log:
      level: info
