apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.health.monitoring.coreos.com.Prometheus: |
    hs = {}
    if obj.status ~= nil and obj.status.conditions ~= nil then
      for _, c in ipairs(obj.status.conditions) do
        if c.type == "Available" then
          if c.status == "True" then
            hs.status = "Healthy"
            hs.message = c.message
            return hs
          else
            hs.status = "Progressing"
            hs.message = c.message
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for Prometheus to become Available"
    return hs

  resource.customizations.health.integreatly.org.Grafana: |
    hs = {}
    if obj.status ~= nil and obj.status.conditions ~= nil then
      for _, c in ipairs(obj.status.conditions) do
        if c.type == "Ready" then
          if c.status == "True" then
            hs.status = "Healthy"
            hs.message = c.message
            return hs
          else
            hs.status = "Progressing"
            hs.message = c.message
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for Grafana to be Ready"
    return hs
